# Generated by Django 4.1.3 on 2022-11-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ax', models.FloatField()),
                ('Ay', models.FloatField()),
                ('Az', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Velocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vx', models.FloatField()),
                ('Vy', models.FloatField()),
                ('Vz', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Z', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.acceleration')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rocket')),
                ('vel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.velocity')),
            ],
        ),
    ]
