# Generated by Django 4.1.3 on 2022-11-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceleration',
            name='position',
        ),
        migrations.RemoveField(
            model_name='velocity',
            name='position',
        ),
        migrations.AddField(
            model_name='acceleration',
            name='rocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceleration', to='app.rocket'),
        ),
        migrations.AddField(
            model_name='velocity',
            name='rocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='velocity', to='app.rocket'),
        ),
    ]
