# Generated by Django 4.1.3 on 2022-11-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_position_accel_alter_position_rocket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='velocity',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
